// Event Bus — Emissor de eventos basico
// Generated by Legendsclaw Deployer (Story 4.4)

'use strict';

const { EventEmitter } = require('events');

const bus = new EventEmitter();

function emit(eventName, payload) {
  const listeners = bus.listenerCount(eventName);
  if (listeners > 0) {
    console.log(`[EVENT] ${eventName} — session_id: ${payload.session_id || 'unknown'} (${listeners} listener(s))`);
    bus.emit(eventName, payload);
  } else {
    console.log(`[EVENT] No listeners for ${eventName} (event logged only)`);
  }
}

function on(eventName, handler) {
  bus.on(eventName, handler);
}

function off(eventName, handler) {
  bus.off(eventName, handler);
}

module.exports = { emit, on, off, bus };
