// Supabase REST Client — Lightweight (fetch nativo, sem SDK)
// Generated by Legendsclaw Deployer (Story 4.2)

'use strict';

const config = (() => {
  try { return require('../../config'); } catch { return {}; }
})();

const SUPABASE_URL = process.env.SUPABASE_URL || config.SUPABASE_URL || '';
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || config.SUPABASE_SERVICE_ROLE_KEY || '';

function getHeaders() {
  if (!SUPABASE_KEY) {
    throw new Error(
      'SUPABASE_SERVICE_ROLE_KEY nao configurada. ' +
      'Verifique .env ou execute Ferramenta [09] Skills com supabase-query.'
    );
  }
  return {
    'apikey': SUPABASE_KEY,
    'Authorization': `Bearer ${SUPABASE_KEY}`,
    'Content-Type': 'application/json',
    'Prefer': 'return=representation',
  };
}

function buildUrl(table, filters) {
  if (!SUPABASE_URL) {
    throw new Error(
      'SUPABASE_URL nao configurada. ' +
      'Verifique .env ou execute Ferramenta [09] Skills com supabase-query.'
    );
  }
  let url = `${SUPABASE_URL}/rest/v1/${encodeURIComponent(table)}`;
  if (filters && typeof filters === 'object') {
    const params = new URLSearchParams();
    for (const [key, value] of Object.entries(filters)) {
      params.append(key, String(value));
    }
    const qs = params.toString();
    if (qs) url += `?${qs}`;
  }
  return url;
}

function sanitize(value) {
  if (value === null || value === undefined) return value;
  if (typeof value === 'string') {
    // Remove null bytes and trim excessive length
    return value.replace(/\0/g, '').slice(0, 10000);
  }
  if (typeof value === 'object') {
    if (Array.isArray(value)) return value.map(sanitize);
    const clean = {};
    for (const [k, v] of Object.entries(value)) {
      clean[sanitize(k)] = sanitize(v);
    }
    return clean;
  }
  return value;
}

async function request(url, method, body) {
  const opts = {
    method,
    headers: getHeaders(),
  };
  if (body !== undefined) {
    opts.body = JSON.stringify(sanitize(body));
  }

  let res;
  try {
    res = await fetch(url, opts);
  } catch (err) {
    throw new Error(
      `Supabase indisponivel (${err.message}). ` +
      `Verifique SUPABASE_URL: ${SUPABASE_URL}`
    );
  }

  const text = await res.text();
  if (!res.ok) {
    // Check for table not found
    if (text.includes('relation') && text.includes('does not exist')) {
      throw new Error(
        'Tabelas de elicitation nao encontradas — execute Story 4.3 ou aplique a migration SQL. ' +
        `Detalhe: ${text}`
      );
    }
    throw new Error(`Supabase error ${res.status}: ${text}`);
  }

  if (!text) return null;
  try { return JSON.parse(text); } catch { return text; }
}

async function select(table, filters) {
  const url = buildUrl(table, filters);
  return request(url, 'GET');
}

async function insert(table, data) {
  const url = buildUrl(table);
  return request(url, 'POST', data);
}

async function update(table, filters, data) {
  const url = buildUrl(table, filters);
  return request(url, 'PATCH', data);
}

async function query(table, method, params) {
  switch (method) {
    case 'GET': return select(table, params);
    case 'POST': return insert(table, params);
    case 'PATCH': return update(table, params.filters, params.data);
    default: throw new Error(`Metodo nao suportado: ${method}`);
  }
}

async function ping() {
  if (!SUPABASE_URL || !SUPABASE_KEY) {
    return { ok: false, error: 'SUPABASE_URL ou SUPABASE_SERVICE_ROLE_KEY ausente' };
  }
  try {
    const res = await fetch(`${SUPABASE_URL}/rest/v1/`, { headers: getHeaders() });
    return { ok: res.status === 200, status: res.status };
  } catch (err) {
    return { ok: false, error: err.message };
  }
}

async function tablesExist() {
  try {
    await select('elicitation_templates', { 'select': 'id', 'limit': '1' });
    return { ok: true };
  } catch (err) {
    return { ok: false, error: err.message };
  }
}

module.exports = { select, insert, update, query, ping, tablesExist, sanitize };
