// Memory Writer — Grava resultados no Memory Manager
// Generated by Legendsclaw Deployer (Story 4.4)

'use strict';

const fs = require('fs');
const path = require('path');

const MEMORY_BASE = path.join(process.env.HOME || '~', '.clawd', 'memory', 'elicitation');

// Map section names to memory file types
const SECTION_MAP = {
  'founder & story': 'User',
  'founder': 'User',
  'fundador': 'User',
  'empresa & tecnico': 'Company',
  'empresa': 'Company',
  'company': 'Company',
  'techstack': 'TechStack',
  'tech': 'TechStack',
  'tecnico': 'TechStack',
  'technical': 'TechStack',
};

function classifySection(sectionName) {
  const lower = (sectionName || '').toLowerCase().trim();
  for (const [key, type] of Object.entries(SECTION_MAP)) {
    if (lower.includes(key)) return type;
  }
  // Default: if first section → User, second → Company, third+ → TechStack
  return null;
}

function formatField(question, answer) {
  if (answer === null || answer === undefined || answer === '') return null;
  return `- **${question}**: ${answer}`;
}

function generateMarkdown(title, sessionId, fields) {
  const lines = [
    `# ${title}`,
    `> Auto-generated by Elicitation Skill`,
    `> Session: ${sessionId}`,
    `> Date: ${new Date().toISOString()}`,
    '',
  ];

  for (const field of fields) {
    if (field) lines.push(field);
  }

  return lines.join('\n') + '\n';
}

async function writeMemoryFiles(sessionResults) {
  const sessionId = sessionResults.session_id || 'unknown';
  const sections = sessionResults.sections || [];
  const isPartial = sessionResults.partial === true;
  const suffix = isPartial ? '-partial' : '';

  // Ensure directory exists
  fs.mkdirSync(MEMORY_BASE, { recursive: true });

  const fileData = { User: [], Company: [], TechStack: [] };

  // Classify sections into memory file types
  sections.forEach((section, idx) => {
    let type = classifySection(section.name);
    if (!type) {
      // Fallback by index
      const types = ['User', 'Company', 'TechStack'];
      type = types[idx] || 'TechStack';
    }

    const fields = (section.fields || [])
      .map(f => formatField(f.question, f.answer))
      .filter(Boolean);

    if (fields.length > 0) {
      fileData[type].push(`## ${section.name}`);
      fileData[type].push(...fields);
      fileData[type].push('');
    }
  });

  const writtenFiles = [];

  for (const [type, fields] of Object.entries(fileData)) {
    if (fields.length === 0) continue;

    const filename = `${type}${suffix}.md`;
    const filepath = path.join(MEMORY_BASE, filename);

    // Backup existing file
    if (fs.existsSync(filepath)) {
      const bakPath = filepath + '.bak';
      fs.copyFileSync(filepath, bakPath);
      try { fs.chmodSync(bakPath, 0o600); } catch { /* ignore */ }
    }

    const content = generateMarkdown(type, sessionId, fields);
    fs.writeFileSync(filepath, content, { mode: 0o600 });
    writtenFiles.push(filename);
  }

  return {
    memory_files: writtenFiles,
    memory_path: MEMORY_BASE,
    partial: isPartial,
  };
}

module.exports = { writeMemoryFiles, MEMORY_BASE, classifySection };
