// Tool: create_skill — Scaffold a new skill with SKILL.md + index.js + tools/
// Generated by Legendsclaw Deployer (Story 12.11)

'use strict';

const fs = require('fs');
const path = require('path');

const VALID_NAME_RE = /^[a-z][a-z0-9-]*$/;
const VALID_CATEGORIES = ['dev', 'infrastructure', 'memory', 'orchestration', 'superpowers', 'system'];
const VALID_TIERS = ['budget', 'standard', 'premium'];
const SAFE_TEXT_RE = /^[a-zA-Z0-9 _.,()\-:!?/]+$/;

function generateSkillMd({ skill_name, description, tier, always_on }) {
  return `---
name: ${skill_name}
description: ${description}
version: 1.0.0
tier: ${tier}
always_on: ${always_on}
---

# ${skill_name.split('-').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ')}

${description}

## Capabilities
- TODO: Define skill capabilities

## Configuration
- No external dependencies
`;
}

function generateIndexJs({ skill_name, description, tier }) {
  return `// Skill: ${skill_name}
// Generated by Legendsclaw Skill Creator

'use strict';

module.exports = {
  name: '${skill_name}',
  description: '${description}',
  tier: '${tier}',

  handler: async (input) => {
    // TODO: Implement ${skill_name} handler
    throw new Error('${skill_name} handler not implemented');
  },

  health: async () => {
    try {
      return { ok: true };
    } catch (err) {
      return { ok: false, error: err.message };
    }
  },
};
`;
}

async function createSkill(params) {
  const {
    skill_name,
    category,
    description,
    tier = 'standard',
    always_on = false,
  } = params || {};

  // Validate required params
  if (!skill_name) {
    throw new Error('skill_name is required');
  }
  if (!category) {
    throw new Error('category is required');
  }
  if (!description) {
    throw new Error('description is required');
  }

  // Validate skill_name format
  if (!VALID_NAME_RE.test(skill_name)) {
    throw new Error(
      `Invalid skill_name "${skill_name}". Must match /^[a-z][a-z0-9-]*$/ (lowercase, starts with letter, only letters/digits/hyphens)`
    );
  }

  // Validate category
  if (!VALID_CATEGORIES.includes(category)) {
    throw new Error(
      `Invalid category "${category}". Must be one of: ${VALID_CATEGORIES.join(', ')}`
    );
  }

  // Validate tier
  if (!VALID_TIERS.includes(tier)) {
    throw new Error(
      `Invalid tier "${tier}". Must be one of: ${VALID_TIERS.join(', ')}`
    );
  }

  // Sanitize description (prevents template injection in generated JS/MD)
  if (!SAFE_TEXT_RE.test(description)) {
    throw new Error(
      `Invalid description "${description}". Must contain only alphanumeric characters, spaces, and basic punctuation`
    );
  }

  // Resolve skills root (two levels up from skill-creator/tools/)
  const skillsRoot = path.resolve(__dirname, '..', '..', '..');
  const skillDir = path.join(skillsRoot, category, skill_name);

  // Check for duplicates
  if (fs.existsSync(skillDir)) {
    throw new Error(
      `Skill "${skill_name}" already exists in category "${category}" at ${skillDir}`
    );
  }

  // Create directory structure
  const toolsDir = path.join(skillDir, 'tools');
  fs.mkdirSync(toolsDir, { recursive: true });

  // Generate files
  const skillMdContent = generateSkillMd({ skill_name, description, tier, always_on });
  const indexJsContent = generateIndexJs({ skill_name, description, tier });

  fs.writeFileSync(path.join(skillDir, 'SKILL.md'), skillMdContent, 'utf8');
  fs.writeFileSync(path.join(skillDir, 'index.js'), indexJsContent, 'utf8');
  fs.writeFileSync(path.join(toolsDir, '.gitkeep'), '', 'utf8');

  const filesCreated = [
    path.join(skillDir, 'SKILL.md'),
    path.join(skillDir, 'index.js'),
    path.join(toolsDir, '.gitkeep'),
  ];

  return {
    success: true,
    skill_name,
    category,
    path: skillDir,
    files_created: filesCreated,
  };
}

module.exports = createSkill;
