// Tool: get_status — Retorna progresso da sessao
// Generated by Legendsclaw Deployer (Story 4.2)

'use strict';

const db = require('../lib/supabase-client');

async function getStatus(sessionId) {
  if (!sessionId) throw new Error('session_id e obrigatorio');

  // Buscar sessao
  const sessions = await db.select('elicitation_sessions', {
    'id': `eq.${sessionId}`,
    'select': '*',
  });

  if (!sessions || sessions.length === 0) {
    throw new Error(`Sessao nao encontrada: ${sessionId}`);
  }

  const session = sessions[0];

  // Buscar template
  const templates = await db.select('elicitation_templates', {
    'id': `eq.${session.template_id}`,
    'select': '*',
  });

  const template = (templates && templates.length > 0) ? templates[0] : null;
  const sections = template ? (template.sections || []) : [];

  // Calcular progresso por secao
  const responses = session.responses || {};
  let totalQuestions = 0;
  let totalAnswered = 0;

  const sectionStatus = sections.map((section, sIdx) => {
    const questions = section.questions || [];
    const sectionResponses = responses[sIdx] || {};
    const answered = Object.keys(sectionResponses).length;
    totalQuestions += questions.length;
    totalAnswered += answered;

    return {
      name: section.name || `Secao ${sIdx + 1}`,
      questions_answered: answered,
      questions_total: questions.length,
      fields: questions.map((q, qIdx) => {
        const resp = sectionResponses[qIdx];
        return {
          question: q.text,
          answered: !!resp,
          value_preview: resp ? String(resp.value || '').slice(0, 50) : null,
        };
      }),
    };
  });

  return {
    session_id: sessionId,
    template_id: session.template_id,
    status: session.status,
    progress_percent: totalQuestions > 0 ? Math.round((totalAnswered / totalQuestions) * 100) : 0,
    sections: sectionStatus,
    created_at: session.created_at,
    updated_at: session.updated_at,
  };
}

module.exports = getStatus;
