// Tool: start_session — Inicia sessao de entrevista
// Generated by Legendsclaw Deployer (Story 4.2)

'use strict';

const db = require('../lib/supabase-client');

async function startSession(templateId) {
  if (!templateId) {
    throw new Error('template_id e obrigatorio');
  }

  // Buscar template
  const templates = await db.select('elicitation_templates', {
    'id': `eq.${templateId}`,
    'select': '*',
  });

  if (!templates || templates.length === 0) {
    throw new Error(`Template nao encontrado: ${templateId}`);
  }

  const template = templates[0];
  const sections = template.sections || [];

  // Calcular total de perguntas
  let totalQuestions = 0;
  for (const section of sections) {
    totalQuestions += (section.questions || []).length;
  }

  // Criar sessao
  const sessionData = {
    template_id: templateId,
    status: 'in_progress',
    current_section: 0,
    current_question: 0,
    responses: {},
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  };

  const result = await db.insert('elicitation_sessions', sessionData);
  const session = Array.isArray(result) ? result[0] : result;

  // Extrair primeira pergunta
  const firstQuestion = sections.length > 0 && sections[0].questions && sections[0].questions.length > 0
    ? sections[0].questions[0]
    : null;

  return {
    session_id: session.id,
    template_id: templateId,
    status: 'in_progress',
    current_question: firstQuestion ? {
      text: firstQuestion.text,
      type: firstQuestion.type || 'text',
      required: firstQuestion.required !== false,
      hints: firstQuestion.hints || null,
    } : null,
    total_questions: totalQuestions,
    progress: 0,
  };
}

module.exports = startSession;
