/**
 * Legendsclaw Command Safety — Pre-tool validation
 * Generated by deployer ferramenta [12] Seguranca
 *
 * Le blocklist.yaml e faz regex matching contra comandos recebidos.
 * Retorna block/allow + loga tentativa.
 */
const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');

const BLOCKLIST_PATH = path.join(__dirname, 'blocklist.yaml');

let cachedBlocklist = null;

function loadBlocklist() {
  if (cachedBlocklist) return cachedBlocklist;
  try {
    const content = fs.readFileSync(BLOCKLIST_PATH, 'utf8');
    const parsed = yaml.load(content);
    cachedBlocklist = (parsed.blocked_commands || []).map(cmd => ({
      pattern: cmd,
      regex: new RegExp(cmd.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i')
    }));
    return cachedBlocklist;
  } catch (err) {
    console.error(`[command-safety] Failed to load blocklist: ${err.message}`);
    return [];
  }
}

function validateCommand(command) {
  const blocklist = loadBlocklist();
  for (const rule of blocklist) {
    if (rule.regex.test(command)) {
      const result = {
        allowed: false,
        blocked_by: rule.pattern,
        command: command,
        timestamp: new Date().toISOString()
      };
      console.error(`[BLOCKED] Command matched rule "${rule.pattern}": ${command}`);
      return result;
    }
  }
  return {
    allowed: true,
    command: command,
    timestamp: new Date().toISOString()
  };
}

function reloadBlocklist() {
  cachedBlocklist = null;
  return loadBlocklist();
}

module.exports = { validateCommand, loadBlocklist, reloadBlocklist };
