// Skill: planner (always-on)
// Generated by Legendsclaw Deployer (Story 12.5)

const fs = require('fs');
const path = require('path');

module.exports = {
  name: 'planner',
  description: 'Task planning and decomposition for complex workflows',
  tier: 'budget',

  handler: async (input) => {
    // TODO: Implement planner handler
    throw new Error('planner handler not implemented');
  },

  health: async () => {
    try {
      const workspaceDir = process.env.AGENT_WORKSPACE || path.join(process.env.HOME || '/root', '.clawd');
      return { ok: fs.existsSync(workspaceDir), path: workspaceDir };
    } catch (err) {
      return { ok: false, error: err.message };
    }
  },
};
