// Skill: elicitation — Entrevistas estruturadas via templates
// Generated by Legendsclaw Deployer (Story 4.2)

'use strict';

const startSession = require('./tools/start-session');
const processMessage = require('./tools/process-message');
const getStatus = require('./tools/get-status');
const exportResults = require('./tools/export-results');
const db = require('./lib/supabase-client');

module.exports = {
  name: 'elicitation',
  description: 'Conduz entrevistas estruturadas via templates',
  tier: 'standard',

  tools: {
    start_session: startSession,
    process_message: processMessage,
    get_status: getStatus,
    export_results: exportResults,
  },

  handler: async (action, params) => {
    switch (action) {
      case 'start_session':
        return startSession(params.template_id);
      case 'process_message':
        return processMessage(params.session_id, params.user_message);
      case 'get_status':
        return getStatus(params.session_id);
      case 'export_results':
        return exportResults(params.session_id, params.format);
      default:
        throw new Error(`Acao desconhecida: ${action}. Acoes validas: start_session, process_message, get_status, export_results`);
    }
  },

  health: async () => {
    const connectivity = await db.ping();
    if (!connectivity.ok) {
      return { ok: false, error: connectivity.error, hint: 'Verifique SUPABASE_URL e SUPABASE_SERVICE_ROLE_KEY' };
    }
    const tables = await db.tablesExist();
    if (!tables.ok) {
      return {
        ok: true,
        warning: 'Supabase acessivel mas tabelas de elicitation nao encontradas — execute Story 4.3',
        connectivity: 'ok',
        tables: 'missing',
      };
    }
    return { ok: true, connectivity: 'ok', tables: 'ok' };
  },
};
