// Skill: context-recovery (always-on)
// Generated by Legendsclaw Deployer (Story 12.5)

const fs = require('fs');
const path = require('path');

module.exports = {
  name: 'context-recovery',
  description: 'Automatic context recovery after session restart',
  tier: 'budget',

  handler: async (input) => {
    const memDir = path.join(process.env.HOME || '/root', '.clawd', 'memory');
    const files = [];

    if (fs.existsSync(memDir)) {
      const entries = fs.readdirSync(memDir).filter(f => f.endsWith('.md'));
      for (const entry of entries) {
        const content = fs.readFileSync(path.join(memDir, entry), 'utf8');
        files.push({ name: entry, content });
      }
    }

    return { recovered: files.length > 0, files: files.length, context: files };
  },

  health: async () => {
    try {
      const memDir = path.join(process.env.HOME || '/root', '.clawd', 'memory');
      if (!fs.existsSync(memDir)) {
        fs.mkdirSync(memDir, { recursive: true });
      }
      return { ok: fs.existsSync(memDir), path: memDir };
    } catch (err) {
      return { ok: false, error: err.message };
    }
  },
};
