#!/usr/bin/env bash
# Session check — Tailscale, Gateway, OpenClaw config, Bridge services
# Generated by setup-local-bridge.sh (Story 12.3)

# 1. Tailscale
TS="offline"
if command -v tailscale &>/dev/null; then
  backend=$(tailscale status --json 2>/dev/null | node -pe 'JSON.parse(require("fs").readFileSync("/dev/stdin","utf8")).BackendState' 2>/dev/null || true)
  [[ "$backend" == "Running" ]] && TS="OK"
fi

# 2. Gateway health (HTTP, timeout 5s)
GW="offline"
if curl -sk --max-time 5 "https://vps-openclaw.tailca0a3e.ts.net/health" &>/dev/null; then
  GW="OK"
fi

# 3. OpenClaw config
OC="not configured"
oc_file="$HOME/.openclaw/openclaw.json"
if [[ -f "$oc_file" ]]; then
  mode=$(node -pe "JSON.parse(require('fs').readFileSync('$oc_file','utf8')).gateway?.mode" 2>/dev/null || true)
  [[ -n "$mode" && "$mode" != "undefined" ]] && OC="$mode"
fi

# 4. Bridge services
svc_count=$(node .aios-core/infrastructure/services/bridge.js list 2>/dev/null | grep -c "  [a-z]" || echo "0")

# 5. SSH to VPS
SSH="offline"
if ssh -o ConnectTimeout=3 -o BatchMode=yes openclaw echo ok &>/dev/null; then
  SSH="OK"
fi

echo "[Bridge] Tailscale: $TS | Gateway: $GW | SSH: $SSH | OpenClaw: $OC | Services: $svc_count"
