// Tool: process_message — Processa resposta e avanca
// Generated by Legendsclaw Deployer (Story 4.2, Updated Story 4.4)

'use strict';

const db = require('../lib/supabase-client');
const { extractData } = require('../lib/llm-extractor');

const MAX_FOLLOWUPS = 2;

async function processMessage(sessionId, userMessage, agentName) {
  if (!sessionId) throw new Error('session_id e obrigatorio');
  if (userMessage === undefined || userMessage === null) {
    throw new Error('user_message e obrigatorio');
  }

  // Buscar sessao
  const sessions = await db.select('elicitation_sessions', {
    'id': `eq.${sessionId}`,
    'select': '*',
  });

  if (!sessions || sessions.length === 0) {
    throw new Error(`Sessao nao encontrada: ${sessionId}`);
  }

  const session = sessions[0];

  // Pausar
  if (userMessage === '__PAUSE__') {
    if (session.status === 'completed') {
      throw new Error('Sessao ja esta completa, nao pode ser pausada');
    }
    await db.update('elicitation_sessions',
      { 'id': `eq.${sessionId}` },
      { status: 'paused', updated_at: new Date().toISOString() }
    );
    const pauseTemplates = await db.select('elicitation_templates', {
      'id': `eq.${session.template_id}`,
      'select': '*',
    });
    let pauseTotal = 0;
    if (pauseTemplates && pauseTemplates.length > 0) {
      for (const s of (pauseTemplates[0].sections || [])) {
        pauseTotal += (s.questions || []).length;
      }
    }
    const pauseAnswered = countAnswered(session.responses);
    return {
      session_id: sessionId,
      status: 'paused',
      next_question: null,
      progress_percent: pauseTotal > 0 ? Math.round((pauseAnswered / pauseTotal) * 100) : 0,
      questions_answered: pauseAnswered,
      questions_total: pauseTotal,
    };
  }

  // Retomar se pausada
  if (session.status === 'paused') {
    session.status = 'in_progress';
  }

  // Validar status
  if (session.status === 'completed') {
    throw new Error('Sessao ja esta completa');
  }
  if (session.status !== 'in_progress') {
    throw new Error(`Status invalido: ${session.status}`);
  }

  // Buscar template
  const templates = await db.select('elicitation_templates', {
    'id': `eq.${session.template_id}`,
    'select': '*',
  });

  if (!templates || templates.length === 0) {
    throw new Error(`Template nao encontrado: ${session.template_id}`);
  }

  const template = templates[0];
  const sections = template.sections || [];
  let sectionIdx = session.current_section || 0;
  let questionIdx = session.current_question || 0;

  // Calcular total de perguntas
  let totalQuestions = 0;
  for (const s of sections) {
    totalQuestions += (s.questions || []).length;
  }

  // Get current question
  const currentSection = sections[sectionIdx];
  const currentQuestions = currentSection ? (currentSection.questions || []) : [];
  const currentQuestion = currentQuestions[questionIdx] || { text: '', type: 'text' };

  // Track follow-ups per question
  const followups = session.followups || {};
  const followupKey = `${sectionIdx}_${questionIdx}`;
  const followupCount = followups[followupKey] || 0;

  // --- LLM Extraction (Story 4.4) ---
  let extractionResult;
  let extractionMethod = 'basic';
  let confidence = null;

  try {
    extractionResult = await extractData(currentQuestion, userMessage, currentQuestion.type || 'text', agentName);

    if (extractionResult.fallback) {
      // LLM unavailable — basic extraction
      extractionMethod = 'basic';
    } else if (extractionResult.extracted) {
      // High confidence
      extractionMethod = 'llm';
      confidence = extractionResult.confidence;
    } else if (followupCount >= MAX_FOLLOWUPS) {
      // Max follow-ups reached — accept as best_effort
      extractionMethod = 'best_effort';
      confidence = extractionResult.confidence;
    } else {
      // Low confidence — send follow-up
      followups[followupKey] = followupCount + 1;

      await db.update('elicitation_sessions',
        { 'id': `eq.${sessionId}` },
        { followups, updated_at: new Date().toISOString() }
      );

      const answered = countAnswered(session.responses || {});
      return {
        session_id: sessionId,
        status: 'in_progress',
        next_question: {
          text: extractionResult.followUp,
          type: currentQuestion.type || 'text',
          required: currentQuestion.required !== false,
          hints: currentQuestion.hints || null,
          is_followup: true,
        },
        progress_percent: totalQuestions > 0 ? Math.round((answered / totalQuestions) * 100) : 0,
        questions_answered: answered,
        questions_total: totalQuestions,
      };
    }
  } catch {
    // Fallback to basic on any error
    extractionMethod = 'basic';
  }

  // Salvar resposta
  const responses = session.responses || {};
  if (!responses[sectionIdx]) responses[sectionIdx] = {};

  const extractedValue = (extractionMethod === 'llm' || extractionMethod === 'best_effort')
    && extractionResult && extractionResult.value !== undefined
    ? extractionResult.value
    : db.sanitize(String(userMessage));

  responses[sectionIdx][questionIdx] = {
    value: extractedValue,
    raw_message: db.sanitize(String(userMessage)),
    extraction_method: extractionMethod,
    confidence: confidence,
    extracted_at: new Date().toISOString(),
  };

  // Avancar para proxima pergunta
  questionIdx++;
  if (questionIdx >= currentQuestions.length) {
    sectionIdx++;
    questionIdx = 0;
  }

  // Verificar se terminou
  let status = 'in_progress';
  let nextQuestion = null;

  if (sectionIdx >= sections.length) {
    status = 'completed';
  } else {
    const nextSection = sections[sectionIdx];
    const nextQuestions = nextSection ? (nextSection.questions || []) : [];
    if (questionIdx < nextQuestions.length) {
      const q = nextQuestions[questionIdx];
      nextQuestion = {
        text: q.text,
        type: q.type || 'text',
        required: q.required !== false,
        hints: q.hints || null,
      };
    } else {
      status = 'completed';
    }
  }

  // Atualizar sessao
  await db.update('elicitation_sessions',
    { 'id': `eq.${sessionId}` },
    {
      status,
      current_section: sectionIdx,
      current_question: questionIdx,
      responses,
      followups,
      updated_at: new Date().toISOString(),
    }
  );

  const answered = countAnswered(responses);

  return {
    session_id: sessionId,
    status,
    next_question: nextQuestion,
    progress_percent: totalQuestions > 0 ? Math.round((answered / totalQuestions) * 100) : 0,
    questions_answered: answered,
    questions_total: totalQuestions,
  };
}

function countAnswered(responses) {
  if (!responses || typeof responses !== 'object') return 0;
  let count = 0;
  for (const section of Object.values(responses)) {
    if (section && typeof section === 'object') {
      count += Object.keys(section).length;
    }
  }
  return count;
}

module.exports = processMessage;
