'use strict';

// Service: vps-remote — SSH Connectivity to VPS
// Generated by Legendsclaw Deployer

const { execSync } = require('child_process');

module.exports = {
  name: 'vps-remote',
  description: 'SSH connectivity to VPS via openclaw alias',

  health: async () => {
    const start = Date.now();

    try {
      execSync('ssh -o ConnectTimeout=5 -o BatchMode=yes openclaw echo ok', {
        timeout: 10000,
        stdio: ['pipe', 'pipe', 'pipe'],
      });
      const latency_ms = Date.now() - start;
      const status = latency_ms > 3000 ? 'degraded' : 'ok';
      return { status, latency_ms, details: 'SSH connection successful' };
    } catch (err) {
      const latency_ms = Date.now() - start;
      return { status: 'down', latency_ms, error: err.message.split('\n')[0] };
    }
  },
};
