#!/usr/bin/env bash
# =============================================================================
# VPS Operations — SSH wrapper for common OpenClaw VPS commands
# Generated by Legendsclaw Deployer
# =============================================================================
set -euo pipefail

SSH_ALIAS="openclaw"
AUDIT_LOG="${HOME}/legendsclaw-logs/vps-ops-audit.log"
STATE_FILE="${HOME}/dados_vps/dados_vps_ssh"

# Resolve SSH target: prefer alias from ~/.ssh/config, fallback to state file
resolve_ssh_target() {
  # Check if openclaw alias exists in ssh config
  if ssh -G "$SSH_ALIAS" 2>/dev/null | grep -q "^hostname"; then
    echo "$SSH_ALIAS"
    return
  fi

  # Fallback: read from state file
  if [[ -f "$STATE_FILE" ]]; then
    local user host
    user=$(grep "^SSH User:" "$STATE_FILE" 2>/dev/null | awk -F': ' '{print $2}' || echo "root")
    host=$(grep "^SSH Host:" "$STATE_FILE" 2>/dev/null | awk -F': ' '{print $2}' || true)
    if [[ -n "$host" ]]; then
      echo "${user}@${host}"
      return
    fi
  fi

  echo "$SSH_ALIAS"
}

TARGET=$(resolve_ssh_target)

# Audit log
audit() {
  mkdir -p "$(dirname "$AUDIT_LOG")"
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] cmd=$1 target=$TARGET user=$(whoami)" >> "$AUDIT_LOG"
}

# SSH wrapper
run_ssh() {
  ssh -o ConnectTimeout=10 -o BatchMode=yes "$TARGET" "$@"
}

usage() {
  cat <<'EOF'
VPS Operations — SSH wrapper for OpenClaw VPS

Usage: vps-ops.sh <command> [args]

Commands:
  status              Show OpenClaw service status (systemctl)
  restart             Restart OpenClaw service
  logs [N]            Show last N lines of OpenClaw logs (default: 50)
  config              Show OpenClaw configuration
  health              Check gateway health endpoint
  skills-list         List installed skills
  skills-info <name>  Show SKILL.md for a specific skill
  disk                Show disk usage
  uptime              Show VPS uptime
  exec <cmd>          Execute arbitrary command on VPS (audit logged)
  --help              Show this help

Examples:
  vps-ops.sh status
  vps-ops.sh logs 100
  vps-ops.sh skills-info mcporter
  vps-ops.sh exec "docker ps"
EOF
}

# Main
cmd="${1:-}"
shift 2>/dev/null || true

case "$cmd" in
  status)
    audit "status"
    run_ssh "systemctl is-active openclaw 2>/dev/null || echo inactive"
    ;;
  restart)
    audit "restart"
    run_ssh "systemctl restart openclaw"
    echo "OpenClaw service restarted."
    ;;
  logs)
    lines="${1:-50}"
    audit "logs:${lines}"
    run_ssh "journalctl -u openclaw --no-pager -n ${lines}"
    ;;
  config)
    audit "config"
    run_ssh "cat ~/.openclaw/openclaw.json 2>/dev/null || echo 'Config not found'"
    ;;
  health)
    audit "health"
    run_ssh "curl -sf http://localhost:18789/health 2>/dev/null || echo 'Health check failed'"
    ;;
  skills-list)
    audit "skills-list"
    run_ssh "ls /opt/openclaw/skills/ 2>/dev/null || echo 'No skills directory found'"
    ;;
  skills-info)
    name="${1:-}"
    if [[ -z "$name" ]]; then
      echo "Usage: vps-ops.sh skills-info <skill-name>"
      exit 1
    fi
    audit "skills-info:${name}"
    run_ssh "cat /opt/openclaw/skills/${name}/SKILL.md 2>/dev/null || echo 'Skill not found: ${name}'"
    ;;
  disk)
    audit "disk"
    run_ssh "df -h / /opt/openclaw 2>/dev/null || df -h /"
    ;;
  uptime)
    audit "uptime"
    run_ssh "uptime"
    ;;
  exec)
    remote_cmd="$*"
    if [[ -z "$remote_cmd" ]]; then
      echo "Usage: vps-ops.sh exec <command>"
      exit 1
    fi
    audit "exec:${remote_cmd}"
    run_ssh "$remote_cmd"
    ;;
  --help|-h|help|"")
    usage
    ;;
  *)
    echo "Unknown command: $cmd"
    echo "Run 'vps-ops.sh --help' for usage."
    exit 1
    ;;
esac
