// Skill: skill-creator — Dynamic skill creation and scaffolding
// Generated by Legendsclaw Deployer (Story 12.11)

'use strict';

const createSkill = require('./tools/create-skill');

module.exports = {
  name: 'skill-creator',
  description: 'Creates new skills dynamically with proper SKILL.md, index.js, and scaffolding',
  tier: 'standard',

  tools: {
    create_skill: createSkill,
  },

  handler: async (action, params) => {
    switch (action) {
      case 'create_skill':
        return createSkill(params);
      default:
        throw new Error(`Unknown action: ${action}. Valid actions: create_skill`);
    }
  },

  health: async () => {
    try {
      const path = require('path');
      const fs = require('fs');
      const skillsRoot = path.resolve(__dirname, '..', '..');
      const canAccess = fs.existsSync(skillsRoot);
      return { ok: canAccess, skills_root: skillsRoot };
    } catch (err) {
      return { ok: false, error: err.message };
    }
  },
};
