#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# Legendsclaw Deployer — Ferramenta 12: Bridge — Claude Code Integration
# Story 5.3: Integrar agente com Claude Code via Bridge.js e Hooks
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIB_DIR="${SCRIPT_DIR}/../lib"

# Source libs
source "${LIB_DIR}/ui.sh"
source "${LIB_DIR}/logger.sh"
source "${LIB_DIR}/common.sh"
source "${LIB_DIR}/auto.sh"
source "${LIB_DIR}/hints.sh"
source "${LIB_DIR}/env-detect.sh"

# =============================================================================
# STEP 1: LOGGING + STEP INIT
# =============================================================================
log_init "bridge"
[[ "${AUTO_MODE:-false}" == "true" ]] && auto_load_config
setup_trap
step_init 10

# =============================================================================
# STEP 2: VERIFICAR DEPENDENCIAS
# =============================================================================

# Node.js
if ! command -v node &>/dev/null; then
  step_fail "Node.js nao encontrado (requer v18+)"
  echo "  Instale: curl -fsSL https://deb.nodesource.com/setup_18.x | sudo bash -"
  exit 1
fi

node_version=$(node --version | sed 's/v//' | cut -d. -f1)
if [[ "$node_version" -lt 18 ]]; then
  step_fail "Node.js versao ${node_version} (requer v18+)"
  exit 1
fi

# Whitelabel (nome do agente)
dados
if [[ ! -f "$STATE_DIR/dados_whitelabel" ]]; then
  step_fail "Whitelabel nao encontrado (~/dados_vps/dados_whitelabel ausente)"
  echo "  Execute primeiro: Ferramenta [07] Whitelabel — Identidade do Agente"
  exit 1
fi
nome_agente=$(grep "Agente:" "$STATE_DIR/dados_whitelabel" | awk -F': ' '{print $2}')
if [[ -z "$nome_agente" ]]; then
  step_fail "Nome do agente nao encontrado em dados_whitelabel"
  exit 1
fi

# OpenClaw Gateway
if [[ ! -f "$STATE_DIR/dados_openclaw" ]]; then
  step_fail "OpenClaw Gateway nao configurado (~/dados_vps/dados_openclaw ausente)"
  echo "  Execute primeiro: Ferramenta [05] OpenClaw Gateway"
  exit 1
fi
gateway_url=$(grep "Gateway URL:" "$STATE_DIR/dados_openclaw" 2>/dev/null | awk -F': ' '{print $2}')
gateway_url="${gateway_url:-http://localhost:18789}"

# Tailscale
tailscale_connected="false"
if command -v tailscale &>/dev/null; then
  if tailscale status &>/dev/null; then
    tailscale_connected="true"
  fi
fi

if [[ "$tailscale_connected" == "true" ]]; then
  step_ok "Dependencias verificadas — Node $(node --version), agente '${nome_agente}', Tailscale conectado"
else
  step_ok "Dependencias verificadas — Node $(node --version), agente '${nome_agente}' (Tailscale desconectado — WARNING)"
  echo -e "  ${UI_YELLOW}WARNING: Tailscale nao conectado. Bridge funcionara, mas health checks remotos podem falhar.${UI_NC}"
fi

# =============================================================================
# STEP 3: CONFERINDO AS INFO
# =============================================================================
conferindo_as_info \
  "Agente=${nome_agente}" \
  "Gateway URL=${gateway_url}" \
  "Tailscale=${tailscale_connected}"

auto_confirm "As informacoes estao corretas? (s/n): " confirma
if ! [[ "$confirma" =~ ^[Ss]$ ]]; then
  echo "Cancelado pelo usuario."
  exit 0
fi
step_ok "Informacoes confirmadas"

# =============================================================================
# STEP 4: CRIAR SERVICE INDEX DO AGENTE
# =============================================================================
SERVICES_DIR=".aios-core/infrastructure/services"
AGENT_SERVICE_DIR="${SERVICES_DIR}/${nome_agente}"

mkdir -p "$AGENT_SERVICE_DIR"

cat > "${AGENT_SERVICE_DIR}/index.js" << JSEOF
'use strict';

// Service: ${nome_agente} — OpenClaw Gateway Health Check
// Generated by Legendsclaw Deployer (Story 5.3)

const http = require('http');
const https = require('https');

const GATEWAY_URL = process.env.OPENCLAW_GATEWAY_URL
  || process.env.AGENT_GATEWAY_URL
  || '${gateway_url}';

const DEGRADED_THRESHOLD_MS = 2000;

module.exports = {
  name: '${nome_agente}',
  description: 'OpenClaw Gateway health for ${nome_agente}',

  health: async () => {
    const url = new URL(GATEWAY_URL + '/health');
    const mod = url.protocol === 'https:' ? https : http;

    const start = Date.now();

    return new Promise((resolve) => {
      const req = mod.get(url, { timeout: 5000 }, (res) => {
        const latency_ms = Date.now() - start;
        let body = '';
        res.on('data', (chunk) => { body += chunk; });
        res.on('end', () => {
          if (res.statusCode === 200) {
            const status = latency_ms > DEGRADED_THRESHOLD_MS ? 'degraded' : 'ok';
            resolve({ status, latency_ms, details: body.slice(0, 100) });
          } else {
            resolve({ status: 'down', latency_ms, details: 'HTTP ' + res.statusCode });
          }
        });
      });

      req.on('error', (err) => {
        const latency_ms = Date.now() - start;
        resolve({ status: 'down', latency_ms, error: err.message });
      });

      req.on('timeout', () => {
        req.destroy();
        const latency_ms = Date.now() - start;
        resolve({ status: 'down', latency_ms, error: 'timeout' });
      });
    });
  },
};
JSEOF

step_ok "Service index criado: ${AGENT_SERVICE_DIR}/index.js"

# =============================================================================
# STEP 5: CRIAR/ATUALIZAR BRIDGE.JS CORE
# =============================================================================
BRIDGE_FILE="${SERVICES_DIR}/bridge.js"

if [[ -f "$BRIDGE_FILE" ]]; then
  step_skip "bridge.js ja existe em ${BRIDGE_FILE}"
else
  step_fail "bridge.js nao encontrado em ${BRIDGE_FILE}"
  echo "  Copie do repositorio: .aios-core/infrastructure/services/bridge.js"
  exit 1
fi

# =============================================================================
# STEP 6: CONFIGURAR CLAUDE CODE HOOKS
# =============================================================================
SETTINGS_FILE=".claude/settings.json"

if [[ -f "$SETTINGS_FILE" ]]; then
  # Check if hooks already configured
  if grep -q "bridge.js" "$SETTINGS_FILE" 2>/dev/null; then
    step_skip "Hooks ja configurados em ${SETTINGS_FILE}"
  else
    # Backup and update
    cp -p "$SETTINGS_FILE" "${SETTINGS_FILE}.bak"
    cat > "$SETTINGS_FILE" << 'JSONEOF'
{
  "language": "portuguese",
  "hooks": {
    "SessionStart": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "node .aios-core/infrastructure/services/bridge.js status 2>/dev/null || echo '[Bridge] Offline — VPN may be disconnected'"
          }
        ]
      }
    ],
    "PreToolUse": [
      {
        "matcher": "Bash",
        "hooks": [
          {
            "type": "command",
            "command": "node .aios-core/infrastructure/services/bridge.js validate-call 2>/dev/null || true"
          }
        ]
      }
    ],
    "PostToolUse": [
      {
        "matcher": "Bash",
        "hooks": [
          {
            "type": "command",
            "command": "node .aios-core/infrastructure/services/bridge.js log-execution 2>/dev/null || true"
          }
        ]
      }
    ]
  }
}
JSONEOF
    step_ok "Hooks configurados em ${SETTINGS_FILE} (backup em .bak)"
  fi
else
  mkdir -p "$(dirname "$SETTINGS_FILE")"
  cat > "$SETTINGS_FILE" << 'JSONEOF'
{
  "language": "portuguese",
  "hooks": {
    "SessionStart": [
      {
        "hooks": [
          {
            "type": "command",
            "command": "node .aios-core/infrastructure/services/bridge.js status 2>/dev/null || echo '[Bridge] Offline — VPN may be disconnected'"
          }
        ]
      }
    ],
    "PreToolUse": [
      {
        "matcher": "Bash",
        "hooks": [
          {
            "type": "command",
            "command": "node .aios-core/infrastructure/services/bridge.js validate-call 2>/dev/null || true"
          }
        ]
      }
    ],
    "PostToolUse": [
      {
        "matcher": "Bash",
        "hooks": [
          {
            "type": "command",
            "command": "node .aios-core/infrastructure/services/bridge.js log-execution 2>/dev/null || true"
          }
        ]
      }
    ]
  }
}
JSONEOF
  step_ok "Hooks configurados em ${SETTINGS_FILE} (novo arquivo)"
fi

# =============================================================================
# STEP 7: TESTAR BRIDGE.JS STATUS E LIST
# =============================================================================
echo ""
echo "  Testando bridge.js..."

bridge_status_ok="false"
bridge_list_ok="false"

# Test list
if node "${BRIDGE_FILE}" list 2>/dev/null; then
  bridge_list_ok="true"
fi

# Test status (may fail if gateway offline — that's expected)
if node "${BRIDGE_FILE}" status 2>/dev/null; then
  bridge_status_ok="true"
fi

if [[ "$bridge_list_ok" == "true" ]]; then
  step_ok "bridge.js list funcional"
else
  step_fail "bridge.js list falhou"
fi

if [[ "$bridge_status_ok" == "true" ]]; then
  step_ok "bridge.js status funcional (gateway pode estar offline)"
else
  step_ok "bridge.js status executou (gateway pode estar offline — normal se Tailscale desconectado)"
fi

# =============================================================================
# STEP 8: SALVAR ESTADO
# =============================================================================
mkdir -p "$STATE_DIR"

services_count=$(node "${BRIDGE_FILE}" list 2>/dev/null | grep -c "  [a-z]" || echo "0")

cat > "$STATE_DIR/dados_bridge" << EOF
Agente: ${nome_agente}
Gateway URL: ${gateway_url}
Bridge Status: configurado
Hooks Configured: true
Services Count: ${services_count}
Tailscale: ${tailscale_connected}
Bridge File: ${BRIDGE_FILE}
Settings File: ${SETTINGS_FILE}
Service Dir: ${AGENT_SERVICE_DIR}
Data Configuracao: $(date '+%Y-%m-%d %H:%M:%S')
EOF
chmod 600 "$STATE_DIR/dados_bridge"

step_ok "Estado salvo em ~/dados_vps/dados_bridge"

# =============================================================================
# STEP 9: HINTS
# =============================================================================
hint_bridge_status "${nome_agente}"
hint_bridge_hooks
hint_bridge_debug "${nome_agente}" "${gateway_url}"

# =============================================================================
# STEP 10: RESUMO FINAL
# =============================================================================
resumo_final

echo -e "${UI_BOLD}  Bridge — Claude Code Integration${UI_NC}"
echo ""
echo "  Agente:        ${nome_agente}"
echo "  Gateway:       ${gateway_url}"
echo "  Tailscale:     ${tailscale_connected}"
echo "  Services:      ${services_count}"
echo ""
echo "  Bridge:        ${BRIDGE_FILE}"
echo "  Service:       ${AGENT_SERVICE_DIR}/index.js"
echo "  Settings:      ${SETTINGS_FILE}"
echo "  Estado:        ~/dados_vps/dados_bridge"
echo "  Log:           ${LOG_FILE}"
echo ""

log_finish
