#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# Legendsclaw Deployer — Ferramenta 12: Seguranca (3 Layers)
# Story 5.2: Blocklist + Sandbox + Logging
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LIB_DIR="${SCRIPT_DIR}/../lib"

# Source libs
source "${LIB_DIR}/ui.sh"
source "${LIB_DIR}/logger.sh"
source "${LIB_DIR}/common.sh"
source "${LIB_DIR}/hints.sh"
source "${LIB_DIR}/env-detect.sh"

# =============================================================================
# CONSTANTES
# =============================================================================
readonly FERRAMENTA="seguranca"
readonly TOTAL=11

# =============================================================================
# STEP 1: LOGGING + RESOURCE GATE
# =============================================================================
log_init "$FERRAMENTA"
setup_trap
step_init "$TOTAL"

if ! recursos 0 0; then
  step_fail "Resource gate falhou"
  exit 1
fi
step_ok "Resource gate — operacoes de configuracao apenas"

# =============================================================================
# STEP 2: LOAD STATE
# =============================================================================
dados
if [[ ! -f "$STATE_DIR/dados_vps" ]]; then
  step_fail "Estado base nao encontrado (~/dados_vps/dados_vps ausente)"
  echo "  Execute primeiro: Ferramenta [01] Traefik + Portainer (base)"
  exit 1
fi
step_ok "Estado base carregado"

# =============================================================================
# STEP 3: VERIFICAR DEPENDENCIA OPENCLAW
# =============================================================================
if [[ ! -f "$STATE_DIR/dados_openclaw" ]]; then
  step_fail "OpenClaw Gateway nao encontrado (~/dados_vps/dados_openclaw ausente)"
  echo "  Execute primeiro: Ferramenta [05] OpenClaw Gateway"
  exit 1
fi
step_ok "Dependencia OpenClaw Gateway verificada"

# Carregar nome do agente (whitelabel)
nome_agente="legendsclaw"
if [[ -f "$STATE_DIR/dados_whitelabel" ]]; then
  nome_agente_tmp=$(grep "Agente:" "$STATE_DIR/dados_whitelabel" 2>/dev/null | awk -F': ' '{print $2}')
  if [[ -n "$nome_agente_tmp" ]]; then
    nome_agente="$nome_agente_tmp"
  fi
fi

# =============================================================================
# STEP 4: LAYER 1 — BLOCKLIST / COMMAND SAFETY
# =============================================================================

# Diretorio destino da blocklist
blocklist_dir="apps/${nome_agente}/skills/lib"
mkdir -p "$blocklist_dir"

# Gerar blocklist.yaml com regras default
cat > "${blocklist_dir}/blocklist.yaml" << 'BLOCKLIST_EOF'
# Legendsclaw Command Safety — Blocklist
# Generated by deployer ferramenta [12] Seguranca
# Edite este arquivo para customizar regras de bloqueio

blocked_commands:
  - rm -rf
  - sudo su
  - dd if=
  - mkfs
  - iptables -F

validation:
  - Regex matching antes de executar comandos
  - Whitelist de comandos permitidos por skill
  - Logging de tentativas bloqueadas
BLOCKLIST_EOF

# Exibir regras ao operador
echo ""
echo -e "${UI_BOLD}=============================================="
echo "  LAYER 1: BLOCKLIST — REGRAS DEFAULT"
echo -e "==============================================${UI_NC}"
echo ""
echo -e "  Comandos bloqueados:"
echo -e "    ${UI_RED}rm -rf${UI_NC}         — Remocao recursiva forcada"
echo -e "    ${UI_RED}sudo su${UI_NC}        — Elevacao de privilegio"
echo -e "    ${UI_RED}dd if=${UI_NC}         — Acesso direto a disco"
echo -e "    ${UI_RED}mkfs${UI_NC}           — Formatacao de filesystem"
echo -e "    ${UI_RED}iptables -F${UI_NC}    — Flush de regras de firewall"
echo ""
echo "=============================================="
echo ""

# Customizacao interativa
read -rp "Deseja customizar as regras? (s/n): " customizar
if [[ "$customizar" =~ ^[Ss]$ ]]; then
  while true; do
    echo ""
    echo "  1) Adicionar regra"
    echo "  2) Remover regra"
    echo "  3) Ver regras atuais"
    echo "  4) Concluir customizacao"
    read -rp "  Opcao: " opcao_custom

    case "$opcao_custom" in
      1)
        read -rp "  Comando a bloquear: " novo_comando
        if [[ -n "$novo_comando" ]]; then
          # Adicionar antes da linha "validation:"
          sed -i "/^validation:/i\\  - ${novo_comando}" "${blocklist_dir}/blocklist.yaml"
          echo -e "  ${UI_GREEN}Adicionado:${UI_NC} ${novo_comando}"
        fi
        ;;
      2)
        read -rp "  Comando a desbloquear: " rm_comando
        if [[ -n "$rm_comando" ]]; then
          sed -i "/^  - ${rm_comando}$/d" "${blocklist_dir}/blocklist.yaml"
          echo -e "  ${UI_YELLOW}Removido:${UI_NC} ${rm_comando}"
        fi
        ;;
      3)
        echo ""
        grep "^  - " "${blocklist_dir}/blocklist.yaml" | head -20
        echo ""
        ;;
      4)
        break
        ;;
      *)
        echo "  Opcao invalida"
        ;;
    esac
  done
fi

# Contar regras
num_regras=$(grep -c "^  - " "${blocklist_dir}/blocklist.yaml" 2>/dev/null || echo 0)
# Descontar as 3 linhas de validation
num_regras_block=$((num_regras - 3))
if [[ $num_regras_block -lt 0 ]]; then
  num_regras_block=0
fi

# Gerar command-safety.js
cat > "${blocklist_dir}/command-safety.js" << 'SAFETY_EOF'
/**
 * Legendsclaw Command Safety — Pre-tool validation
 * Generated by deployer ferramenta [12] Seguranca
 *
 * Le blocklist.yaml e faz regex matching contra comandos recebidos.
 * Retorna block/allow + loga tentativa.
 */
const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');

const BLOCKLIST_PATH = path.join(__dirname, 'blocklist.yaml');

let cachedBlocklist = null;

function loadBlocklist() {
  if (cachedBlocklist) return cachedBlocklist;
  try {
    const content = fs.readFileSync(BLOCKLIST_PATH, 'utf8');
    const parsed = yaml.load(content);
    cachedBlocklist = (parsed.blocked_commands || []).map(cmd => ({
      pattern: cmd,
      regex: new RegExp(cmd.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i')
    }));
    return cachedBlocklist;
  } catch (err) {
    console.error(`[command-safety] Failed to load blocklist: ${err.message}`);
    return [];
  }
}

function validateCommand(command) {
  const blocklist = loadBlocklist();
  for (const rule of blocklist) {
    if (rule.regex.test(command)) {
      const result = {
        allowed: false,
        blocked_by: rule.pattern,
        command: command,
        timestamp: new Date().toISOString()
      };
      console.error(`[BLOCKED] Command matched rule "${rule.pattern}": ${command}`);
      return result;
    }
  }
  return {
    allowed: true,
    command: command,
    timestamp: new Date().toISOString()
  };
}

function reloadBlocklist() {
  cachedBlocklist = null;
  return loadBlocklist();
}

module.exports = { validateCommand, loadBlocklist, reloadBlocklist };
SAFETY_EOF

chmod 600 "${blocklist_dir}/blocklist.yaml"

step_ok "Layer 1 — Blocklist configurada (${num_regras_block} regras em ${blocklist_dir}/blocklist.yaml)"

# =============================================================================
# STEP 5: LAYER 2 — DOCKER SANDBOX (Dockerfile)
# =============================================================================

# Gerar Dockerfile.sandbox no diretorio do deployer
sandbox_dir="${SCRIPT_DIR}/../sandbox"
mkdir -p "$sandbox_dir"

cat > "${sandbox_dir}/Dockerfile.sandbox" << 'DOCKERFILE_EOF'
FROM alpine:3.19
RUN apk add --no-cache nodejs npm python3 py3-pip
RUN adduser -D sandbox
USER sandbox
WORKDIR /home/sandbox
DOCKERFILE_EOF

# Build da imagem
echo ""
echo "  Construindo imagem Docker sandbox..."
if docker build -t openclaw-sandbox -f "${sandbox_dir}/Dockerfile.sandbox" "${sandbox_dir}" 2>&1; then
  step_ok "Layer 2 — Imagem openclaw-sandbox construida"
else
  step_fail "Layer 2 — Falha ao construir imagem sandbox"
  echo "  Verifique se Docker esta rodando e tente novamente"
  echo "  Manual: docker build -t openclaw-sandbox -f ${sandbox_dir}/Dockerfile.sandbox ${sandbox_dir}"
  # Nao abortar — sandbox pode ser construido depois
fi

# =============================================================================
# STEP 6: LAYER 2 — DEPLOY SANDBOX STACK
# =============================================================================

# Gerar YAML da stack sandbox
cat > "$HOME/sandbox.yaml" << 'SANDBOX_YAML_EOF'
version: "3.8"

services:
  sandbox:
    image: openclaw-sandbox
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
      restart_policy:
        condition: on-failure
        max_attempts: 3
    read_only: true
    networks: []
    tmpfs:
      - /tmp:size=64M

networks: {}
SANDBOX_YAML_EOF

chmod 600 "$HOME/sandbox.yaml"

# Deploy via docker stack
echo ""
echo "  Fazendo deploy da stack sandbox..."
if docker stack deploy -c "$HOME/sandbox.yaml" sandbox 2>&1; then
  # Wait com polling
  echo "  Aguardando container sandbox..."
  attempts=0
  max_attempts=30
  while [[ $attempts -lt $max_attempts ]]; do
    if docker service ls --format "{{.Name}} {{.Replicas}}" 2>/dev/null | grep -q "sandbox_sandbox.*1/1"; then
      break
    fi
    sleep 2
    attempts=$((attempts + 1))
  done

  if [[ $attempts -lt $max_attempts ]]; then
    step_ok "Layer 2 — Sandbox deployada (network:none, read_only, 256m)"
  else
    step_fail "Layer 2 — Sandbox deploy timeout (container nao ficou healthy em 60s)"
    echo "  Verifique: docker service ls | grep sandbox"
  fi
else
  step_fail "Layer 2 — Falha no deploy da stack sandbox"
  echo "  Verifique se Docker Swarm esta ativo"
  echo "  Manual: docker stack deploy -c ~/sandbox.yaml sandbox"
fi

# =============================================================================
# STEP 7: LAYER 3 — JOURNALD (6 meses retencao)
# =============================================================================

echo ""
echo "  Configurando journald para retencao de 6 meses..."

journald_conf_dir="/etc/systemd/journald.conf.d"
journald_conf_file="${journald_conf_dir}/legendsclaw.conf"

if sudo mkdir -p "$journald_conf_dir" 2>/dev/null; then
  sudo tee "$journald_conf_file" > /dev/null << 'JOURNALD_EOF'
[Journal]
MaxRetentionSec=15780000
SystemMaxUse=2G
JOURNALD_EOF

  if sudo systemctl restart systemd-journald 2>/dev/null; then
    step_ok "Layer 3 — journald configurado (retencao 6 meses, max 2GB)"
  else
    step_fail "Layer 3 — Falha ao reiniciar journald"
    echo "  Manual: sudo systemctl restart systemd-journald"
  fi
else
  step_fail "Layer 3 — Sem permissao sudo para configurar journald"
  echo "  Manual: sudo mkdir -p ${journald_conf_dir}"
  echo "  Depois: criar ${journald_conf_file} com MaxRetentionSec=15780000"
fi

# =============================================================================
# STEP 8: LAYER 3 — LOGROTATE (180 dias)
# =============================================================================

echo ""
echo "  Configurando logrotate para 180 dias..."

logrotate_dir="/var/log/legendsclaw"
logrotate_conf="/etc/logrotate.d/legendsclaw"

if sudo mkdir -p "$logrotate_dir" 2>/dev/null; then
  sudo tee "$logrotate_conf" > /dev/null << 'LOGROTATE_EOF'
/var/log/legendsclaw/*.log {
  daily
  rotate 180
  compress
  delaycompress
  missingok
  notifempty
  create 0640 root root
}
LOGROTATE_EOF

  # Testar config
  if sudo logrotate -d "$logrotate_conf" 2>&1 | grep -q "error" 2>/dev/null; then
    step_fail "Layer 3 — Erro na configuracao logrotate"
    echo "  Verifique: sudo logrotate -d ${logrotate_conf}"
  else
    step_ok "Layer 3 — logrotate configurado (180 dias, comprimido)"
  fi
else
  step_fail "Layer 3 — Sem permissao sudo para configurar logrotate"
  echo "  Manual: sudo mkdir -p ${logrotate_dir}"
  echo "  Depois: criar ${logrotate_conf}"
fi

# =============================================================================
# STEP 9: HINTS DE VERIFICACAO
# =============================================================================

hint_seguranca_blocklist "$nome_agente"
hint_seguranca_sandbox
hint_seguranca_logging

step_ok "Hints de verificacao exibidos para as 3 layers"

# =============================================================================
# STEP 10: SALVAR ESTADO
# =============================================================================

cat > "$STATE_DIR/dados_seguranca" << STATE_EOF
Layer 1 (Blocklist): ATIVO
Blocklist Path: apps/${nome_agente}/skills/lib/blocklist.yaml
Command Safety: apps/${nome_agente}/skills/lib/command-safety.js
Regras Bloqueadas: ${num_regras_block}
Layer 2 (Sandbox): ATIVO
Sandbox Image: openclaw-sandbox
Network: none
Read Only: true
Memory Limit: 256m
CPU Limit: 0.5
Layer 3 (Logging): ATIVO
Journald Retention: 6 meses
Logrotate Retention: 180 dias
Log Dir: /var/log/legendsclaw/
Data Configuracao: $(date '+%Y-%m-%d %H:%M:%S')
STATE_EOF

chmod 600 "$STATE_DIR/dados_seguranca"

step_ok "Estado salvo em ~/dados_vps/dados_seguranca"

# =============================================================================
# STEP 11: RESUMO FINAL
# =============================================================================

resumo_final

echo -e "${UI_BOLD}  Seguranca 3 Layers:${UI_NC}"
echo -e "    Layer 1 (Blocklist):  ${UI_GREEN}ATIVO${UI_NC} — ${num_regras_block} regras"
echo -e "    Layer 2 (Sandbox):    ${UI_GREEN}ATIVO${UI_NC} — network:none, read_only, 256m"
echo -e "    Layer 3 (Logging):    ${UI_GREEN}ATIVO${UI_NC} — journald 6m + logrotate 180d"
echo ""
echo "  Estado: ~/dados_vps/dados_seguranca"
echo "  Log:    ${LOG_FILE}"
echo ""

log_finish
